version: '3.8'
services:
  agg:
    container_name: aggregator
    image: aggregator:1.0.0
    build:
      context: .
      target: agg
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env

  postgres:
    container_name: aggregator_postgres
    image: postgres:14
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  redis:
    container_name: aggregator_redis
    image: 'redis:alpine'
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/var/lib/redis
    env_file:
      - ./.env
volumes:
  postgres-data:
  redis-data:
